version: '3.8'

services: 
  my_app:
    image: app:1.0
    build:
      context: .
    ports:
      - 5000:5000
    networks: 
      - custom
    depends_on:
      - mongodb
    environment:
      - MONGO_URL="mongodb://mongodb/"
    

  mongodb:
    image: mongo
    networks: 
      - custom
    ports:
      - 27017:27017
    volumes:
      - ./data/db_data:/data/db_data
  
networks:
  custom:
    driver: bridge

volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      device: /data/db
      o: bind 
